export const productListConst = [
	{
		id: "DUJ3287DNS8SF",
		prdt_img: "/asset/products/grey-top.png",
		prdt_imgXs: "/asset/products/grey-top-xs.png",
		prdt_imgXl: "/asset/products/grey-top-xl.png",
		prdt_title: "Apollo",
		prdt_subTitle: "Running Short",
		prdt_desc:
			"Find stunning women's cocktail dresses and party dresses. Stand out in lace and metallic cocktail dresses and party dresses from all your favorite brands.",
		prdt_color: ["#D3D2D5", "#2B2B2B", "#0F6450"],
		prdt_size: ["XS", "S", "M", "L"],
		prdt_price: 50,
		prdt_instock: true,
	},
	{
		id: "JOIGUFI3493FDF",
		prdt_img: "/asset/products/grey-top.png",
		prdt_imgXs: "/asset/products/grey-top-xs.png",
		prdt_imgXl: "/asset/products/grey-top-xl.png",
		prdt_title: "Apollo",
		prdt_subTitle: "Running Short",
		prdt_desc:
			"Find stunning women's cocktail dresses and party dresses. Stand out in lace and metallic cocktail dresses and party dresses from all your favorite brands.",
		prdt_color: ["#D3D2D5", "#2B2B2B", "#0F6450"],
		prdt_size: ["XS", "S", "M", "L"],
		prdt_price: 50,
		prdt_instock: true,
	},
	{
		id: "BUYW3487GUDSDSF",
		prdt_img: "/asset/products/grey-top.png",
		prdt_imgXs: "/asset/products/grey-top-xs.png",
		prdt_imgXl: "/asset/products/grey-top-xl.png",
		prdt_title: "Apollo",
		prdt_subTitle: "Running Short",
		prdt_desc:
			"Find stunning women's cocktail dresses and party dresses. Stand out in lace and metallic cocktail dresses and party dresses from all your favorite brands.",
		prdt_color: ["#D3D2D5", "#2B2B2B", "#0F6450"],
		prdt_size: ["XS", "S", "M", "L"],
		prdt_price: 50,
		prdt_instock: false,
	},
	{
		id: "634VUSD78E3SDSF",
		prdt_img: "/asset/products/grey-top.png",
		prdt_imgXs: "/asset/products/grey-top-xs.png",
		prdt_imgXl: "/asset/products/grey-top-xl.png",
		prdt_title: "Apollo",
		prdt_subTitle: "Running Short",
		prdt_desc:
			"Find stunning women's cocktail dresses and party dresses. Stand out in lace and metallic cocktail dresses and party dresses from all your favorite brands.",
		prdt_color: ["#D3D2D5", "#2B2B2B", "#0F6450"],
		prdt_size: ["XS", "S", "M", "L"],
		prdt_price: 50,
		prdt_instock: true,
	},
	{
		id: "98SRDFGVSKUEWERK",
		prdt_img: "/asset/products/grey-top.png",
		prdt_imgXs: "/asset/products/grey-top-xs.png",
		prdt_imgXl: "/asset/products/grey-top-xl.png",
		prdt_title: "Apollo",
		prdt_subTitle: "Running Short",
		prdt_desc:
			"Find stunning women's cocktail dresses and party dresses. Stand out in lace and metallic cocktail dresses and party dresses from all your favorite brands.",
		prdt_color: ["#D3D2D5", "#2B2B2B", "#0F6450"],
		prdt_size: ["XS", "S", "M", "L"],
		prdt_price: 50,
		prdt_instock: true,
	},
	{
		id: "RE4342JHSD989DSQW",
		prdt_img: "/asset/products/grey-top.png",
		prdt_imgXs: "/asset/products/grey-top-xs.png",
		prdt_imgXl: "/asset/products/grey-top-xl.png",
		prdt_title: "Apollo",
		prdt_subTitle: "Running Short",
		prdt_desc:
			"Find stunning women's cocktail dresses and party dresses. Stand out in lace and metallic cocktail dresses and party dresses from all your favorite brands.",
		prdt_color: ["#D3D2D5", "#2B2B2B", "#0F6450"],
		prdt_size: ["XS", "S", "M", "L"],
		prdt_price: 50,
		prdt_instock: true,
	},
];
